### ISSUE TITLE
Circular dependency between SnowUtils.h and GenomicRegion.h

### ISSUE THREAD

**Issue by SHuang-Broad** [jwalabroad/SnowTools#2]
Hi Jeremiah,

Just a quick note that there seem to be a circular reference into each other between the two headers.

SnowUtils doesn't seem to need GenomicRegion.

Steve

**Comment by jwalabroad** [comment]
Hi Steve, very good eye. I made the change and will include in the next update. If you're interested in working on SnowTools, let me know (jwala@broadinstitute.org) and I can add you as a collaborator. No problem though if you're just exploring / trying it out instead. I've been working more lately on updating things, testing them, and incorporating new features (e.g. rolling SGA assemblies into this package), so hopefully this will improve quickly.
