### ISSUE TITLE
Implicit conversion from istream to bool

### ISSUE THREAD

**Issue by dodomorandi** [jwalabroad/SnowTools#8]
I found a little problem inside SGA/Util/ClusterRead.cpp (line 70), due to an implicit conversion from istream to bool. It can be easily solved with the following patch:

```
diff --git a/SGA/Util/ClusterReader.cpp b/SGA/Util/ClusterReader.cpp
index 5c9460b..a7367dd 100644
--- a/SGA/Util/ClusterReader.cpp
+++ b/SGA/Util/ClusterReader.cpp
@@ -67,8 +67,8 @@ bool ClusterReader::generate(ClusterVector& out)
 bool ClusterReader::readCluster(ClusterRecord& record)
 {
     std::string line;
-    bool good = getline(*m_pReader, line);
-    if(!good || line.empty())
+    getline(*m_pReader, line);
+    if(!m_pReader->good() || line.empty())
         return false;
     std::stringstream parser(line);
     parser >> record.clusterID;
```

Thank you for efforts with this awesome project!

**Comment by SHuang-Broad** [comment]
Hi @dodomorandi , this is more of an SGA issue, and has been reported [here](https://github.com/jts/sga/issues/108).
But thanks for reporting.

**Comment by jwalabroad** [comment]
Thanks @dodomaroandi and @SHuang-Broad. I made the patch suggested in the SGA report. Hopefully this will compile on your system now Edoardo. Let me know if there are other patches that would be helpful so you can build.
